CXXFLAGS=-O3 -g --std=c++0x -Wall

default:

02-members: 02-members.cpp Integer.cpp
	$(CXX) $^ -o $@

03-static-members: 03-static-members.cpp CountOccurance.cpp
	$(CXX) $^ -o $@

04-lifetime: 04-lifetime.cpp CountOccurance.cpp
	$(CXX) $^ -o $@
